### ISSUE TITLE
Player does not get turn after enemy turn. 

### ISSUE THREAD

**Issue by bagelhobbit** [semaphore-soft/Cypher#10] opened 2017-03-08 19:29 UTC

**Comment by scorple** [comment] 2017-03-08 21:08
Does not appear that this issue is caused by a failure to update host ui when it is host's turn, may require logs for diagnosis.

**Comment by scorple** [comment] 2017-03-09 00:28
Probable cause identified: actor controller does not take an action recognized to complete a turn if the actor is in an 'unplaced' room. In our snapshot of this issue, we generated a room not connected to the dungeon before taking our turns. I hypothesize that there was at least one actor in that disconnected room which could not act and therefore could not end its turn, breaking the turn rotation.

**Comment by scorple** [comment] 2017-03-09 01:30
Fixed in v0.2.2.

**Closed as completed by scorple** 2017-03-09 01:30 UTC
Labels: bug
